# Generated by Django 4.2.2 on 2023-06-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('race', models.CharField(choices=[('Human', 'Human'), ('Fantasy', 'Fantasy'), ('Creature', 'Creature'), ('Alien', 'Alien')], default=None, max_length=50)),
                ('health', models.PositiveIntegerField(default=0)),
                ('attack', models.PositiveIntegerField(default=0)),
                ('deffence', models.PositiveIntegerField(default=0)),
                ('overall', models.PositiveIntegerField(default=0)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('overall_game', models.PositiveIntegerField(default=0)),
                ('health_game', models.PositiveIntegerField(default=0)),
                ('attack_game', models.PositiveIntegerField(default=0)),
                ('deffence_game', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
