# Generated by Django 4.2.2 on 2023-06-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_card_attack_game_remove_card_deffence_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
