# Generated by Django 4.2.2 on 2023-06-12 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_card_attack_ingame_card_deffence_ingame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='attack_ingame',
        ),
        migrations.RemoveField(
            model_name='card',
            name='deffence_ingame',
        ),
        migrations.RemoveField(
            model_name='card',
            name='health_ingame',
        ),
        migrations.RemoveField(
            model_name='card',
            name='overall_ingame',
        ),
    ]
