# Generated by Django 4.2.2 on 2023-06-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_card_attack_ingame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='speed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='tier',
            field=models.IntegerField(blank=True, choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3'), (4, 'Tier 4')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='wins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
