# Generated by Django 4.2.2 on 2023-06-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_card_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='crit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='fatique',
            field=models.IntegerField(default=0),
        ),
    ]
