# Generated by Django 4.2.2 on 2023-07-08 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_initialcards_tournament_winners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slot', models.CharField(choices=[('1', 'Slot 1'), ('2', 'Slot 2'), ('3', 'Slot 3'), ('4', 'Slot 4')], max_length=1)),
                ('save_name', models.CharField(max_length=100)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tournament')),
                ('winners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.winners')),
            ],
        ),
    ]
