# Generated by Django 4.2.2 on 2023-07-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_game_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slot',
        ),
        migrations.AddField(
            model_name='game',
            name='slot_choices',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=0, max_length=1, null=True),
        ),
    ]
