# Generated by Django 4.2.2 on 2023-07-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_remove_game_slot_game_slot_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slot_choices',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True),
        ),
    ]
