# Generated by Django 4.2.2 on 2023-07-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_game_slot_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='save_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
