# Generated by Django 4.2.2 on 2023-07-08 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_game_save_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='save_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.tournament'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winners',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.winners'),
        ),
    ]
