# Generated by Django 4.2.2 on 2023-07-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_game_name_alter_game_save_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
