# Generated by Django 4.2.2 on 2023-07-08 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_delete_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('tournament_data', models.JSONField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tournament')),
                ('winners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.winners')),
            ],
        ),
    ]
