# Generated by Django 4.2.2 on 2023-07-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_gamesave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winners',
            name='tournament',
        ),
        migrations.AddField(
            model_name='winners',
            name='tournament_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='GameSave',
        ),
    ]
