# Generated by Django 4.2.2 on 2023-07-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_remove_winners_tournament_winners_tournament_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winners',
            name='tournament_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tournament'),
        ),
    ]
