# Generated by Django 4.2.2 on 2023-07-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='save_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
