# Generated by Django 4.2.2 on 2023-07-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_world_save_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='World_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
