# Generated by Django 4.2.2 on 2023-07-10 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_world_world_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='world',
            old_name='World_name',
            new_name='world_name',
        ),
    ]
